CREATE TABLE Categories 
(
CategoryID NUMBER(22,8) NOT NULL, 
CategoryName VARCHAR2(15), 
CategoryCode NUMBER(22,6) NULL, 
Description  VARCHAR2(300),
CONSTRAINT Categories_CategoryID_pk PRIMARY KEY (CategoryID)
); 

-- How to set the precison into 6 
/*
ALTER TABLE Categories ALTER COLUMN CategoryCode decimal(6,0);
CategoryCode DECIMAL(6,0);
*/


 CREATE TABLE CUSTOMERS 
 (
 CUSTOMERID CHAR(5) NOT NULL, 
 COMPANYNAME VARCHAR2(40) NOT NULL,
 CONTACTNAME VARCHAR2(30),
 CONTACTTITLE VARCHAR2(30),
 ADDRESS VARCHAR2(60),
 CITY VARCHAR2(15),
 REGION VARCHAR2(15),
 POSTALCODE VARCHAR2(10), 
 COUNTRY VARCHAR2(15),
 PHONE VARCHAR2(24),
 FAX VARCHAR2(24),
 EMAIL VARCHAR2(50),
 CONSTRAINT CUSTOMERS_CUSTOMERID_pk PRIMARY KEY (CUSTOMERID)
 ); 

-- tHIS TABLE IS READY CUSTOMERS


CREATE TABLE Employees
(
 EmployeeID NUMBER(22,8) NOT NULL,
 LastName VARCHAR2(20) NOT NULL, 
 FirstName VARCHAR2(10) NOT NULL, 
 Title VARCHAR2(30), 
 TitleOfCourtesy VARCHAR2(25),
 BirthDate DATE(7), 
 HireDate DATE(7), 
 Address  VARCHAR2(60), 
 City VARCHAR2(15), 
 Region VARCHAR2(15), 
 PostalCode VARCHAR2(10), 
 Country VARCHAR2(15), 
 HomePhone VARCHAR2(24), 
 Extension VARCHAR2(4), 
 Notes VARCHAR2(600), 
 ReportsTo NUMBER(22,8),
 PhotoPath VARCHAR2(255),
 Sin CHAR(9) NULL,
 CONSTRAINT Employees_EmployeeID_pk PRIMARY KEY (EmployeeID)
 );

-- Is there issue with employees table? STh wrong


CREATE TABLE ORDERDETAILS 
(
ORDERID  NUMBER(22,8) NOT NULL, 
PRODUCTID  NUMBER(22,8) NOT NULL, 
UNITPRICE  NUMBER(22,8) NOT NULL, 
QUANTITY  NUMBER(22,8) NOT NULL,
DISCOUNT  NUMBER(22,8) NOT NULL,
CONSTRAINT ORDERDETAILS_ORDERID_pk PRIMARY KEY (ORDERID)
);



CREATE TABLE ORDERS 
(
ORDERID NUMBER(22,0) NOT NULL, 
CUSTOMERID CHAR(5), 
EMPLOYEEID NUMBER(22,0), 
TERRITORYID VARCHAR2(20), 
ORDERDATE  DATE(7), 
REQUIREDDATE  DATE(7), 
SHIPPEDDATE  DATE(7), 
SHIPVIA NUMBER(22,0), 
FREIGHT NUMBER(22,0), 
SHIPNAME VARCHAR2(40), 
SHIPADDRESS VARCHAR2(60), 
SHIPCITY VARCHAR2(15), 
SHIPREGION VARCHAR2(15), 
SHIPPOSTALCODE VARCHAR2(10), 
SHIPCOUNTRY VARCHAR2(15),
CONSTRAINT ORDERS_ORDERID_pk PRIMARY KEY (ORDERID)
);




CREATE TABLE Products
(
ProductID NUMBER(22,0), 
ProductName VARCHAR2(40), 
SupplierID NUMBER(22,0), 
CategoryID NUMBER(22,0), 
QuantityPerUnit VARCHAR2(20), 
UnitPrice NUMBER(22,0), 
UnitsInStock NUMBER(22,0), 
UnitsOnOrder NUMBER(22,0), 
ReorderLevel NUMBER(22,0), 
Discontinued NUMBER(22,0),
CONSTRAINT Products_ProductID_pk PRIMARY KEY (ProductID)
)








